### ISSUE TITLE
define close socket interface

### ISSUE THREAD

**Issue by liva** [Raphine/Raph_Library#28]
killing proc by sending SIGINT causes fuckin' death, which does not release socket.
so we must provide PoolingSocket::Close for app defined signal handler.

**Comment by levelfour** [comment]
This post would be helpful. I have not initialized the 6th arg passed to `recvfrom`.

```
socklen_t sin_size;  // maybe this variable have to be initilaized to sizeof(_udp_client[index].addr)
int32_t rval = recvfrom(_udp_socket, packet->buf, kMaxPacketLength, 0, reinterpret_cast<struct sockaddr *>(&_udp_client[index].addr), &sin_size);
```

http://stackoverflow.com/questions/2999639/recvfrom-returns-invalid-argument-when-from-is-passed

**Comment by levelfour** [comment]
I add `perror` output after `recvfrom`. If fails again, please report it.
